const stateList = [
    { name: 'Alabama', value: 'al' },
    { name: 'Alaska', value: 'ak' },
    { name: 'American Samoa', value: 'as' },
    { name: 'Arizona', value: 'az' },
    { name: 'Arkansas', value: 'ar' },
    { name: 'California', value: 'ca' },
    { name: 'Colorado', value: 'co' },
    { name: 'Connecticut', value: 'ct' },
    { name: 'Delaware', value: 'de' },
    { name: 'District of Columbia', value: 'dc' },
    { name: 'Florida', value: 'fl' },
    { name: 'Georgia', value: 'ga' },
    { name: 'Guam', value: 'gu' },
    { name: 'Hawaii', value: 'hi' },
    { name: 'Idaho', value: 'id' },
    { name: 'Illinois', value: 'il' },
    { name: 'Indiana', value: 'in' },
    { name: 'Iowa', value: 'ia' },
    { name: 'Kansas', value: 'ks' },
    { name: 'Kentucky', value: 'ky' },
    { name: 'Louisiana', value: 'la' },
    { name: 'Maine', value: 'me' },
    { name: 'Maryland', value: 'md' },
    { name: 'Massachusetts', value: 'ma' },
    { name: 'Michigan', value: 'mi' },
    { name: 'Minnesota', value: 'mn' },
    { name: 'Mississippi', value: 'ms' },
    { name: 'Missouri', value: 'mo' },
    { name: 'Montana', value: 'mt' },
    { name: 'Nebraska', value: 'ne' },
    { name: 'Nevada', value: 'nv' },
    { name: 'New Hampshire', value: 'nh' },
    { name: 'New Jersey', value: 'nj' },
    { name: 'New Mexico', value: 'nm' },
    { name: 'New York', value: 'ny' },
    { name: 'North Carolina', value: 'nc' },
    { name: 'North Dakota', value: 'nd' },
    { name: 'Ohio', value: 'oh' },
    { name: 'Oklahoma', value: 'ok' },
    { name: 'Oregon', value: 'or' },
    { name: 'Pennsylvania', value: 'pa' },
    { name: 'Puerto Rico', value: 'pr' },
    { name: 'Rhode Island', value: 'ri' },
    { name: 'South Carolina', value: 'sc' },
    { name: 'South Dakota', value: 'sd' },
    { name: 'Tennessee', value: 'tn' },
    { name: 'Texas', value: 'tx' },
    { name: 'Utah', value: 'ut' },
    { name: 'Vermont', value: 'vt' },
    { name: 'Virgin Islands', value: 'vi' },
    { name: 'Virginia', value: 'va' },
    { name: 'Washington', value: 'wa' },
    { name: 'West Virginia', value: 'wv' },
    { name: 'Wisconsin', value: 'wi' },
    { name: 'Wyoming', value: 'wy' },
];